<?php
declare(strict_types=1);

$head = <<<'HTML'
<meta charset="utf-8"/><meta content="width=device-width,initial-scale=1" name="viewport"/><link href="assets/images/logo/fire-dine-site-icon.webp" rel="icon" type="image/webp"/><link href="assets/images/logo/fire-dine-site-icon.webp" rel="apple-touch-icon"/><title>Checkout | Fire &amp; Dine</title><meta content="Premium wood-fired ovens, fireplaces and installations in South Africa." name="description"/><link href="assets/fonts/fontawesome/css/all.min.css" rel="stylesheet"/><link href="assets/css/fire-dine-premium.css" rel="stylesheet"/><link href="/assets/css/design-system.css" rel="stylesheet"/>
HTML;
$header = <<<'HTML'
<div class="page"><header class="header"><div class="shell"><a class="logo" href="/"><img alt="Fire &amp; Dine — Family Time Since 2013" src="assets/images/logo/fire-dine-header-logo.webp"/></a><button aria-expanded="false" aria-label="Open navigation" class="menu-btn"><i class="fas fa-bars"></i></button><nav aria-label="Primary navigation" class="nav"><a href="/">Home</a><a href="/about">About Us</a><a href="/shop">Shop</a><a href="/installation">Installation</a><a href="/gallery">Gallery</a><a href="/contact">Contact Us</a></nav><a aria-label="Cart" class="cart-link" href="/cart"><i class="fas fa-shopping-cart"></i><span class="badge">0</span></a></div></header>
HTML;
$main = <<<'HTML'
<main><section class="page-hero hero-image-selected" style="--hero-desktop:url('/assets/images/hero-selected/shop-product-showcase-1920.webp');--hero-tablet:url('/assets/images/hero-selected/shop-product-showcase-1440.webp');--hero-mobile:url('/assets/images/hero-selected/shop-product-showcase-960.webp');--hero-position:center center;--hero-position-mobile:55% center;"><div class="shell"><span class="eyebrow">Quote-led ordering</span><h1>Request a Quotation</h1><p>Online checkout requirements are still to be confirmed. Fire and Dine currently handles quotations directly.</p></div></section><section class="section"><div class="shell"><div class="content-box" style="max-width:860px;margin:auto;text-align:center"><h2>Ordering is currently handled directly</h2><p>The knowledge-transfer record does not confirm public VAT treatment, universal payment terms or whether online checkout is part of the new site. To avoid presenting unverified commercial terms, please request a current quotation directly from Fire and Dine.</p><div class="actions" style="justify-content:center"><a class="btn btn-gold" href="/contact?subject=quote">Request a Quote</a><a class="btn btn-outline" href="https://wa.me/27834381485">WhatsApp 083 438 1485</a></div></div></div></section><section class="cta site-final-cta" style="background-image:linear-gradient(rgba(5,6,6,.78),rgba(5,6,6,.92)),url('assets/images/fire-and-dine/cta/cta-05-request-quote.webp');"><div class="shell"><span class="eyebrow">Start your project</span><h2>Bring Your Fire &amp; Dine Space to Life</h2><p>Tell us about your space, preferred product and location, and our team will help you plan the right next step.</p><div class="actions"><a class="btn btn-gold" href="/contact?subject=quote">Request a Quote</a></div></div></section></main>
HTML;
$footer = <<<'HTML'
<footer class="footer"><div class="shell footer-grid"><div class="footer-col footer-brand"><img alt="Fire &amp; Dine — Family Time Since 2013" class="footer-logo" src="assets/images/logo/fire-dine-footer-logo.webp"/></div><div class="footer-col"><h3>Quick Links</h3><a href="/installation#maintenance"><i aria-hidden="true" class="fas fa-wrench gold"></i><span>Maintenance</span></a><a href="/contact"><i aria-hidden="true" class="fas fa-phone gold"></i><span>Contact Us</span></a><a href="/"><i aria-hidden="true" class="fas fa-home gold"></i><span>Home</span></a><a href="/shop"><i aria-hidden="true" class="fas fa-shopping-bag gold"></i><span>Shop</span></a><a href="/stoneskin">StoneSkin</a></div><div class="footer-col footer-contact"><h3>Contact Us</h3><p><i aria-hidden="true" class="fas fa-map-marker-alt gold"></i><span>Vanderbijlpark, Gauteng</span></p><a href="tel:+27834381485"><i aria-hidden="true" class="fas fa-phone gold"></i><span>083 438 1485</span></a><a href="mailto:Info@fireanddine.co.za"><i aria-hidden="true" class="fas fa-envelope gold"></i><span>Info@fireanddine.co.za</span></a></div><div class="footer-col"><h3>Connect</h3><div class="socials"><a aria-label="Contact Fire &amp; Dine" href="/contact"><i class="fab fa-facebook-f"></i></a><a aria-label="Contact Fire &amp; Dine" href="/contact"><i class="fab fa-instagram"></i></a><a aria-label="Contact Fire &amp; Dine" href="/contact"><i class="fab fa-youtube"></i></a></div></div><div class="footer-col policy-links"><h3>Policies</h3><a href="/privacy-policy"><i aria-hidden="true" class="fas fa-user-shield gold"></i><span>Privacy Policy</span></a><a href="/terms"><i aria-hidden="true" class="fas fa-file-contract gold"></i><span>Terms of Service</span></a></div></div><div class="copyright"><span>© South Africa <span data-year=""></span></span><span class="copyright-sep">|</span><span>All Rights Reserved</span><span></span><span class="copyright-sep">|</span><a class="gold" href="/terms">Terms &amp; Conditions</a><span class="copyright-sep">|</span><a class="gold" href="/privacy-policy">Privacy Policy</a></div></footer></div>
HTML;
$scripts = <<<'HTML'
<script src="assets/js/fire-dine-premium.js"></script><script src="/assets/js/x3-tracking.js"></script><script src="/assets/js/brochure-widget.js"></script>
HTML;
require dirname(__DIR__) . '/layouts/app.php';
