<?php
declare(strict_types=1);

$bodyAttributes = ' data-landing="commercial"';
$head = <<<'HTML'
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="assets/images/logo/fire-dine-site-icon.webp" rel="icon" type="image/webp"><link href="assets/images/logo/fire-dine-site-icon.webp" rel="apple-touch-icon"><title>Commercial Pizza Ovens | Fire &amp; Dine</title><meta name="description" content="Discuss commercial pizza oven capacity, cooking output, installation space and delivery requirements with Fire &amp; Dine."><link href="https://fireanddine.co.za/commercial-ovens" rel="canonical"><link href="assets/fonts/fontawesome/css/all.min.css" rel="stylesheet"><link href="assets/css/fire-dine-premium.css" rel="stylesheet"><link href="/assets/css/design-system.css" rel="stylesheet"/>
HTML;
$header = <<<'HTML'
<div class="page"><header class="header"><div class="shell"><a class="logo" href="/"><img alt="Fire &amp; Dine — Family Time Since 2013" src="assets/images/logo/fire-dine-header-logo.webp"></a><button aria-expanded="false" aria-label="Open navigation" class="menu-btn"><i class="fas fa-bars"></i></button><nav aria-label="Primary navigation" class="nav"><a href="/">Home</a><a href="/about">About Us</a><a href="/shop">Shop</a><a href="/installation">Installation</a><a href="/gallery">Gallery</a><a href="/contact">Contact Us</a></nav><a aria-label="Cart" class="cart-link" href="/cart"><i class="fas fa-shopping-cart"></i><span class="badge">0</span></a></div></header>
HTML;
$main = <<<'HTML'
<main>
    <section class="page-hero hero-image-selected" style="--hero-desktop:url('assets/images/fire-and-dine/range-heroes/commercial-pizza-ovens-1916.webp');--hero-tablet:url('assets/images/fire-and-dine/range-heroes/commercial-pizza-ovens-1440.webp');--hero-mobile:url('assets/images/fire-and-dine/range-heroes/commercial-pizza-ovens-960.webp');--hero-position:center center;--hero-position-mobile:64% center;"><div class="shell"><span class="eyebrow">Restaurants, hospitality and catering</span><h1>Commercial Pizza Ovens Built for Serious Service</h1><p>Plan around business type, expected output, cooking capacity, installation space and delivery access.</p><div class="actions"><a class="btn btn-gold" href="#commercial-form">Request a Commercial Quote</a><a class="btn btn-outline" href="tel:+27834381485">Discuss Your Requirements</a></div></div></section>
    <section class="section"><div class="shell"><header class="section-head"><span class="eyebrow">Qualification</span><h2>Start With the Service Requirement</h2><p>The right recommendation depends on how the oven will be used, not only its appearance.</p></header><div class="cards"><article class="content-box"><h2>Business Type</h2><p>Restaurant, lodge, hospitality venue, caterer or mobile food operation.</p></article><article class="content-box"><h2>Expected Output</h2><p>Share expected service volume, menu requirements and peak periods.</p></article><article class="content-box"><h2>Space and Access</h2><p>Provide installation measurements, delivery access and available services.</p></article></div></div></section>
    <section class="section fd-alt-white"><div class="shell two-col"><div><header class="section-head aligned-left"><span class="eyebrow">Commercial consultation</span><h2>Discuss Your Oven Requirements</h2><p>Submit the core project information and the team will continue the conversation directly.</p></header></div><form action="/thank-you" class="content-box commercial-form" id="commercial-form" method="get"><label>Business type<select class="form-control" name="businessType" required><option value="">Select</option><option>Restaurant</option><option>Hospitality or lodge</option><option>Catering</option><option>Mobile food service</option><option>Other</option></select></label><label>Expected cooking volume<input class="form-control" name="volume" required></label><label>Available installation space<input class="form-control" name="space" required></label><label>Delivery location<input class="form-control" name="location" required></label><label>Project notes<textarea class="form-control" name="notes"></textarea></label><button class="btn btn-gold" type="submit">Request a Commercial Quote</button></form></div></section>
    <section class="section" data-kt-integrated="true"><div class="shell"><header class="section-head"><span class="eyebrow">Commercial ranges</span><h2>Match Capacity to the Service You Run</h2><p>Pre-Fabricato and Neapolitan ovens cover different footprints and pizza volumes. Fire and Dine can also build commercial ovens with hybrid gas-and-wood operation.</p></header><div class="spec-groups"><div><h3>Pre-Fabricato</h3><ul><li><strong>Medium:</strong> 2&ndash;3 medium pizzas</li><li><strong>Large:</strong> 3 large pizzas</li><li><strong>XL:</strong> 4&ndash;5 pizzas</li><li><strong>XXL:</strong> 6&ndash;7 pizzas</li></ul></div><div><h3>Neapolitan</h3><ul><li><strong>Piccolo:</strong> 2&ndash;3 medium pizzas</li><li><strong>Classico:</strong> 4 pizzas</li><li><strong>Grande:</strong> 6&ndash;7 pizzas</li><li><strong>Maestro:</strong> 8&ndash;10 pizzas</li></ul></div></div><p class="supporting-note"><strong>Hybrid commercial builds:</strong> the burner is fitted and tested before dispatch. Final specification is confirmed for the project.</p></div></section>
    <section class="section fd-alt-white" data-kt-integrated="true"><div class="shell"><header class="section-head"><span class="eyebrow">Make the client the hero</span><h2>Brand the Oven Into the Venue</h2><p>Custom mosaic is available in unlimited colour combinations, including company logos tiled directly into the dome. This gives restaurants, franchise groups and hospitality venues a functional centrepiece that belongs to the brand.</p></header><div class="supporting-note"><p>Commercial ovens are manufactured and finished in-house, delivered nationwide and can be supplied for export into Africa. Delivery and installation are quoted separately.</p></div><div class="supporting-note"><strong>Commercial proof:</strong> Fire and Dine records include repeat business from Mikes Kitchen Potchefstroom and branded mosaic oven projects for KwikSpar and Stoetbul.</div></div></section>
    <section class="cta site-final-cta" style="background-image:linear-gradient(rgba(5,6,6,.78),rgba(5,6,6,.92)),url('assets/images/fire-and-dine/cta/cta-02-shop-pizza-ovens.webp');"><div class="shell"><span class="eyebrow">Commercial support</span><h2>One Clear Next Step</h2><p>Send your service requirements, space and location for a product-specific discussion.</p><div class="actions"><a class="btn btn-gold" href="#commercial-form">Request a Commercial Quote</a></div></div></section>
  </main>
HTML;
$footer = <<<'HTML'
<footer class="footer"><div class="shell footer-grid"><div class="footer-col footer-brand"><img alt="Fire &amp; Dine — Family Time Since 2013" class="footer-logo" src="assets/images/logo/fire-dine-footer-logo.webp"></div><div class="footer-col policy-links"><h3>Policies</h3><a href="/privacy-policy"><i aria-hidden="true" class="fas fa-user-shield gold"></i><span>Privacy Policy</span></a><a href="/terms"><i aria-hidden="true" class="fas fa-file-contract gold"></i><span>Terms of Service</span></a></div></div><div class="copyright"><span class="copyright-sep">|</span><a class="gold" href="/privacy-policy">Privacy Policy</a></div></footer></div>
HTML;
$scripts = <<<'HTML'
<script src="assets/js/fire-dine-premium.js"></script><script src="/assets/js/x3-tracking.js"></script><script src="/assets/js/brochure-widget.js"></script>
HTML;
require dirname(__DIR__) . '/layouts/app.php';
