<?php
declare(strict_types=1);

$head = <<<'HTML'
<meta charset="utf-8"/><meta content="width=device-width,initial-scale=1" name="viewport"/><link href="assets/images/logo/fire-dine-site-icon.webp" rel="icon" type="image/webp"/><link href="assets/images/logo/fire-dine-site-icon.webp" rel="apple-touch-icon"/><title>FAQs | Fire &amp; Dine</title><meta content="Answers about Fire &amp; Dine products, delivery, installation, customisation and care." name="description"/><link href="assets/fonts/fontawesome/css/all.min.css" rel="stylesheet"/><link href="assets/css/fire-dine-premium.css" rel="stylesheet"/><link href="/assets/css/design-system.css" rel="stylesheet"/>
HTML;
$header = <<<'HTML'
<div class="page"><header class="header"><div class="shell"><a class="logo" href="/"><img alt="Fire &amp; Dine — Family Time Since 2013" src="assets/images/logo/fire-dine-header-logo.webp"/></a><button aria-expanded="false" aria-label="Open navigation" class="menu-btn"><i class="fas fa-bars"></i></button><nav aria-label="Primary navigation" class="nav"><a href="/">Home</a><a href="/about">About Us</a><a href="/shop">Shop</a><a href="/installation">Installation</a><a href="/gallery">Gallery</a><a href="/contact">Contact Us</a></nav><a aria-label="Cart" class="cart-link" href="/cart"><i class="fas fa-shopping-cart"></i><span class="badge">0</span></a></div></header>
HTML;
$main = <<<'HTML'
<main><section class="page-hero hero-image-selected" style="--hero-desktop:url('assets/images/hero-selected/terms-of-service-1920.webp');--hero-tablet:url('assets/images/hero-selected/terms-of-service-1440.webp');--hero-mobile:url('assets/images/hero-selected/terms-of-service-960.webp');--hero-position:center center;--hero-position-mobile:50% center;"><div class="shell"><span class="eyebrow">Help &amp; Guidance</span><h1>Frequently Asked Questions</h1><p>Clear guidance on choosing, receiving, installing and caring for your Fire &amp; Dine product.</p></div></section><section class="section faq-section"><div class="shell"><div class="faq-list">
<details open=""><summary>Which pizza oven is right for me?<i aria-hidden="true" class="fas fa-plus"></i></summary><p>The right choice depends on space, cooking volume, permanent or mobile placement, preferred fuel, finish and budget. Send us measurements and site photographs for tailored advice.</p></details>
<details><summary>Do you supply commercial pizza ovens?<i aria-hidden="true" class="fas fa-plus"></i></summary><p>Yes. We supply restaurants, caterers, lodges and hospitality venues, with guidance on capacity, cooking surface, installation, finishes and delivery access.</p></details>
<details><summary>Can selected ovens be customised?<i aria-hidden="true" class="fas fa-plus"></i></summary><p>Selected ranges offer smooth or textured finishes, brick-face or mosaic detailing, thermometers, coastal upgrades, mobile stands, side tables and gas options.</p></details>
<details><summary>Do you deliver across South Africa?<i aria-hidden="true" class="fas fa-plus"></i></summary><p>Delivery can be coordinated nationwide. The final quotation depends on product size and weight, destination, route, unloading equipment and site access.</p></details>
<details><summary>Do you provide installation assistance?<i aria-hidden="true" class="fas fa-plus"></i></summary><p>Yes. We can advise on site preparation, supporting bases, clearances, chimneys and flues, placement, curing and commissioning.</p></details>
<details><summary>Does a new pizza oven need to be cured?<i aria-hidden="true" class="fas fa-plus"></i></summary><p>Yes. Refractory ovens require gradual low-temperature firings before full use so retained moisture can escape safely. Follow the product-specific curing schedule supplied.</p></details>
<details><summary>How do I choose the correct fireplace?<i aria-hidden="true" class="fas fa-plus"></i></summary><p>Room size, ceiling height, insulation, layout, heating output and flue route all matter. Share your room dimensions and photographs for an informed recommendation.</p></details>
<details><summary>What wood should I use?<i aria-hidden="true" class="fas fa-plus"></i></summary><p>Use clean, dry, properly seasoned firewood. Never burn treated timber, painted wood, plastic or household waste.</p></details>
<details><summary>Are warranties included?<i aria-hidden="true" class="fas fa-plus"></i></summary><p>Coverage varies by product and component. We confirm the applicable product and workmanship terms before purchase.</p></details>
</div><div class="faq-cta"><span class="eyebrow">Personal guidance</span><h2>Still Have Questions?</h2><p>Speak to our team about your room, venue, cooking needs or installation site.</p><div class="actions"><a class="btn btn-gold" href="/contact">Speak to an Expert</a><a class="btn btn-outline" href="tel:+27834381485">Call 083 438 1485</a></div></div></div></section><section class="cta site-final-cta" style="background-image:linear-gradient(rgba(5,6,6,.78),rgba(5,6,6,.92)),url('assets/images/fire-and-dine/cta/cta-05-request-quote.webp');"><div class="shell"><span class="eyebrow">Start your project</span><h2>Bring Your Fire &amp; Dine Space to Life</h2><p>Tell us about your space, preferred product and location, and our team will help you plan the right next step.</p><div class="actions"><a class="btn btn-gold" href="/contact?subject=quote">Request a Quote</a></div></div></section></main>
HTML;
$footer = <<<'HTML'
<footer class="footer"><div class="shell footer-grid"><div class="footer-col footer-brand"><img alt="Fire &amp; Dine — Family Time Since 2013" class="footer-logo" src="assets/images/logo/fire-dine-footer-logo.webp"/></div><div class="footer-col"><h3>Quick Links</h3><a href="/stoneskin">StoneSkin</a></div><div class="footer-col footer-contact"><h3>Contact Us</h3></div><div class="footer-col"><h3>Stay Connected</h3></div><div class="footer-col policy-links"><h3>Policies</h3><a href="/privacy-policy"><i aria-hidden="true" class="fas fa-user-shield gold"></i><span>Privacy Policy</span></a><a href="/terms"><i aria-hidden="true" class="fas fa-file-contract gold"></i><span>Terms of Service</span></a></div></div><div class="copyright"><span class="copyright-sep">|</span><a class="gold" href="/privacy-policy">Privacy Policy</a></div></footer></div>
HTML;
$scripts = <<<'HTML'
<script src="assets/js/fire-dine-premium.js"></script><script src="/assets/js/x3-tracking.js"></script><script src="/assets/js/brochure-widget.js"></script><script src="/assets/js/stoneskin-brand-cleanup.js"></script>
HTML;
require dirname(__DIR__) . '/layouts/app.php';
