<?php
declare(strict_types=1);

$bodyAttributes = ' data-landing="compact"';
$head = <<<'HTML'
<meta charset="utf-8"/><meta content="width=device-width,initial-scale=1" name="viewport"/><link href="assets/images/logo/fire-dine-site-icon.webp" rel="icon" type="image/webp"/><link href="assets/images/logo/fire-dine-site-icon.webp" rel="apple-touch-icon"/><title>Mobile &amp; Compact Pizza Ovens | Fire &amp; Dine</title><meta content="Explore mobile, compact and countertop pizza oven options for smaller patios and flexible cooking spaces." name="description"/><link href="https://fireanddine.co.za/mobile-compact-ovens" rel="canonical"/><link href="assets/fonts/fontawesome/css/all.min.css" rel="stylesheet"/><link href="assets/css/fire-dine-premium.css" rel="stylesheet"/><link href="/assets/css/design-system.css" rel="stylesheet"/>
HTML;
$header = <<<'HTML'
<div class="page"><header class="header"><div class="shell"><a class="logo" href="/"><img alt="Fire &amp; Dine — Family Time Since 2013" src="assets/images/logo/fire-dine-header-logo.webp"/></a><button aria-expanded="false" aria-label="Open navigation" class="menu-btn"><i class="fas fa-bars"></i></button><nav aria-label="Primary navigation" class="nav"><a href="/">Home</a><a href="/about">About Us</a><a href="/shop">Shop</a><a href="/installation">Installation</a><a href="/gallery">Gallery</a><a href="/contact">Contact Us</a></nav><a aria-label="Cart" class="cart-link" href="/cart"><i class="fas fa-shopping-cart"></i><span class="badge">0</span></a></div></header>
HTML;
$main = <<<'HTML'
<main><section class="page-hero hero-image-selected" style="--hero-desktop:url('assets/images/hero-selected/hero-04-product-showcase-1920.webp');--hero-tablet:url('assets/images/hero-selected/hero-04-product-showcase-1440.webp');--hero-mobile:url('assets/images/hero-selected/hero-04-product-showcase-960.webp');--hero-position:center center;--hero-position-mobile:72% center;"><div class="shell"><span class="eyebrow">Flexible live-fire cooking</span><h1>Mobile &amp; Compact Pizza Ovens</h1><p>Explore smaller-footprint and movable configurations for patios, countertop use and flexible catering setups.</p><div class="actions"><a class="btn btn-gold" href="/shop#pizza-ovens">View Available Products</a><a class="btn btn-outline" href="/contact?product=Mobile%20or%20Compact%20Oven">Request Product Advice</a></div></div></section><section class="section"><div class="shell"><header class="section-head"><span class="eyebrow">Fit and flexibility</span><h2>Choose Around Footprint, Movement and Access</h2><p>Confirm support, total dimensions, safe clearances, delivery access and whether the oven must be repositioned.</p></header><div class="cards"><article class="content-box"><h2>Compact Patios</h2><p>Prioritise usable footprint and safe surrounding clearances.</p></article><article class="content-box"><h2>Countertop Use</h2><p>Confirm the supporting surface and product-specific installation requirements.</p></article><article class="content-box"><h2>Mobile Service</h2><p>Discuss transport, stability, cooking volume and intended operating environment.</p></article></div></div></section><section class="section fd-alt-white" data-kt-integrated="true"><div class="shell"><header class="section-head"><span class="eyebrow">Mobile range</span><h2>Move the Fire Where the Gathering Happens</h2><p>The mobile range combines Fire and Dine ovens with wheeled steel stands for patios, event use and flexible layouts.</p></header><div class="range-cards four"><article><h3>Mobile Countertop</h3><p>A mobile version of the countertop concept on a wheeled steel stand with timber shelving.</p></article><article><h3>Premium Piccolo</h3><p>Compact premium mobile model with wheeled stand and integrated practical storage.</p></article><article><h3>Premium Vivace</h3><p>Mid-size premium mobile model with timber shelving and log storage.</p></article><article><h3>Premium Maestro</h3><p>The largest Premium Mobile model, supplied on a wheeled steel stand with timber shelving and log storage.</p></article></div></div></section><section class="cta site-final-cta" style="background-image:linear-gradient(rgba(5,6,6,.78),rgba(5,6,6,.92)),url('assets/images/fire-and-dine/cta/cta-02-shop-pizza-ovens.webp');"><div class="shell"><h2>Discuss a Flexible Oven Setup</h2><p>Tell us where and how the oven will be used.</p><div class="actions"><a class="btn btn-gold" href="/contact?product=Mobile%20or%20Compact%20Oven">Request Product Advice</a></div></div></section></main>
HTML;
$footer = <<<'HTML'
<footer class="footer"><div class="shell footer-grid"><div class="footer-col footer-brand"><img alt="Fire &amp; Dine — Family Time Since 2013" class="footer-logo" src="assets/images/logo/fire-dine-footer-logo.webp"/></div><div class="footer-col policy-links"><h3>Policies</h3><a href="/privacy-policy"><i aria-hidden="true" class="fas fa-user-shield gold"></i><span>Privacy Policy</span></a><a href="/terms"><i aria-hidden="true" class="fas fa-file-contract gold"></i><span>Terms of Service</span></a></div></div><div class="copyright"><span class="copyright-sep">|</span><a class="gold" href="/privacy-policy">Privacy Policy</a></div></footer></div>
HTML;
$scripts = <<<'HTML'
<script src="assets/js/fire-dine-premium.js"></script><script src="/assets/js/x3-tracking.js"></script><script src="/assets/js/brochure-widget.js"></script>
HTML;
require dirname(__DIR__) . '/layouts/app.php';
