<?php
declare(strict_types=1);

$bodyAttributes = ' data-landing="outdoor"';
$head = <<<'HTML'
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="assets/images/logo/fire-dine-site-icon.webp" rel="icon" type="image/webp"><link href="assets/images/logo/fire-dine-site-icon.webp" rel="apple-touch-icon"><title>Outdoor Models | Fire &amp; Dine</title><meta name="description" content="Explore Fire &amp; Dine outdoor pizza ovens, fireplaces and finishes for patios and entertainment spaces."><link href="https://fireanddine.co.za/outdoor-models" rel="canonical"><link href="assets/fonts/fontawesome/css/all.min.css" rel="stylesheet"><link href="assets/css/fire-dine-premium.css" rel="stylesheet"><link href="/assets/css/design-system.css" rel="stylesheet"/>
HTML;
$header = <<<'HTML'
<div class="page"><header class="header"><div class="shell"><a class="logo" href="/"><img alt="Fire &amp; Dine — Family Time Since 2013" src="assets/images/logo/fire-dine-header-logo.webp"></a><button aria-expanded="false" aria-label="Open navigation" class="menu-btn"><i class="fas fa-bars"></i></button><nav aria-label="Primary navigation" class="nav"><a href="/">Home</a><a href="/about">About Us</a><a href="/shop">Shop</a><a href="/installation">Installation</a><a href="/gallery">Gallery</a><a href="/contact">Contact Us</a></nav><a aria-label="Cart" class="cart-link" href="/cart"><i class="fas fa-shopping-cart"></i><span class="badge">0</span></a></div></header>
HTML;
$main = <<<'HTML'
<main>
    <section class="page-hero hero-image-selected" style="--hero-desktop:url('assets/images/fire-and-dine/range-heroes/outdoor-models-1916.webp');--hero-tablet:url('assets/images/fire-and-dine/range-heroes/outdoor-models-1440.webp');--hero-mobile:url('assets/images/fire-and-dine/range-heroes/outdoor-models-960.webp');--hero-position:center center;--hero-position-mobile:64% center;"><div class="shell"><span class="eyebrow">Outdoor living</span><h1>Outdoor Models Built for Unforgettable Gatherings</h1><p>Explore existing Fire &amp; Dine options for live-fire cooking, warmth and considered outdoor entertainment spaces.</p><div class="actions"><a class="btn btn-gold" href="#outdoor-ranges">Explore Outdoor Options</a><a class="btn btn-outline" href="/contact?product=Outdoor%20Models">Request a Quote</a></div></div></section>
    <section class="section"><div class="shell"><header class="section-head"><span class="eyebrow">Plan the setting</span><h2>Start With How You Use Your Outdoor Space</h2><p>Match the product family to the available footprint, placement, cooking plans and type of entertaining.</p></header><div class="cards"><article class="content-box"><h2>Cooking and Entertaining</h2><p>Consider typical group size, cooking frequency and whether the oven will be built in or movable.</p></article><article class="content-box"><h2>Space and Placement</h2><p>Confirm the footprint, supporting surface, access and relationship to the surrounding entertainment area.</p></article><article class="content-box"><h2>Warmth and Finish</h2><p>Coordinate ovens, Forge fireplaces and available finishes around the materials already used outdoors.</p></article></div></div></section>
    <section class="section fd-alt-white" id="outdoor-ranges"><div class="shell"><header class="section-head"><span class="eyebrow">Existing outdoor ranges</span><h2>Fire &amp; Dine Options for Outdoor Living</h2><p>These existing product families are already used across patios, outdoor kitchens, braai areas, bomas and entertainment spaces.</p></header><div class="knowledge-grid"><article class="content-box"><h3>Domestic &amp; Countertop Ovens</h3><p>DIY Standard, Grande and Superior, plus the Countertop oven for a finished counter or built-in braai top.</p><a class="text-link" href="/residential-pizza-ovens">Explore residential ovens &rarr;</a></article><article class="content-box"><h3>Mobile &amp; Steel Ovens</h3><p>Mobile Countertop, Premium Mobile Piccolo, Vivace and Maestro, plus Small, Medium and Large steel ovens.</p><a class="text-link" href="/mobile-compact-ovens">Explore mobile ovens &rarr;</a></article><article class="content-box"><h3>Forge Fireplaces</h3><p>Freestanding and built-in closed-combustion models for considered residential heating and gathering spaces.</p><a class="text-link" href="/fireplaces">Explore Forge fireplaces &rarr;</a></article><article class="content-box"><h3>StoneSkin Finish</h3><p>Durable decorative stone coating for ovens and suitable patios, entertainment areas, braai and boma walls.</p><a class="text-link" href="/stoneskin">Explore StoneSkin &rarr;</a></article></div></div></section>
    <section class="section"><div class="shell"><header class="section-head"><span class="eyebrow">Project guidance</span><h2>Plan the Product Around the Site</h2><p>Share measurements, photographs, access details and delivery location when requesting guidance.</p></header><div class="fact-grid three"><article><strong>Product</strong><span>Choose around cooking, warmth or both.</span></article><article><strong>Placement</strong><span>Confirm base, clearances and delivery access.</span></article><article><strong>Finish</strong><span>Discuss the options available for the selected model.</span></article></div></div></section>
    <section class="cta site-final-cta" style="background-image:linear-gradient(rgba(5,6,6,.78),rgba(5,6,6,.92)),url('assets/images/fire-and-dine/cta/cta-05-request-quote.webp');"><div class="shell"><span class="eyebrow">Your outdoor project</span><h2>Bring Fire, Food and Outdoor Living Together</h2><p>Tell us about your space, intended use and location for a product-specific conversation.</p><div class="actions"><a class="btn btn-gold" href="/contact?product=Outdoor%20Models">Request a Quote</a></div></div></section>
  </main>
HTML;
$footer = <<<'HTML'
<footer class="footer"><div class="shell footer-grid"><div class="footer-col footer-brand"><img alt="Fire &amp; Dine — Family Time Since 2013" class="footer-logo" src="assets/images/logo/fire-dine-footer-logo.webp"></div><div class="footer-col policy-links"><h3>Policies</h3><a href="/privacy-policy"><i aria-hidden="true" class="fas fa-user-shield gold"></i><span>Privacy Policy</span></a><a href="/terms"><i aria-hidden="true" class="fas fa-file-contract gold"></i><span>Terms of Service</span></a></div></div><div class="copyright"><span class="copyright-sep">|</span><a class="gold" href="/privacy-policy">Privacy Policy</a></div></footer></div>
HTML;
$scripts = <<<'HTML'
<script src="assets/js/fire-dine-premium.js"></script><script src="/assets/js/x3-tracking.js"></script><script src="/assets/js/brochure-widget.js"></script>
HTML;
require dirname(__DIR__) . '/layouts/app.php';
