<?php
declare(strict_types=1);

$head = <<<'HTML'
<meta charset="utf-8"/><meta content="width=device-width,initial-scale=1" name="viewport"/><link href="assets/images/logo/fire-dine-site-icon.webp" rel="icon" type="image/webp"/><link href="assets/images/logo/fire-dine-site-icon.webp" rel="apple-touch-icon"/><title>Privacy Policy | Fire &amp; Dine</title><meta content="Fire &amp; Dine privacy policy." name="description"/><link href="assets/fonts/fontawesome/css/all.min.css" rel="stylesheet"/><link href="assets/css/fire-dine-premium.css" rel="stylesheet"/><link href="/assets/css/design-system.css" rel="stylesheet"/>
HTML;
$header = <<<'HTML'
<div class="page"><header class="header"><div class="shell"><a class="logo" href="/"><img alt="Fire &amp; Dine — Family Time Since 2013" src="assets/images/logo/fire-dine-header-logo.webp"/></a><button aria-expanded="false" aria-label="Open navigation" class="menu-btn"><i class="fas fa-bars"></i></button><nav aria-label="Primary navigation" class="nav"><a href="/">Home</a><a href="/about">About Us</a><a href="/shop">Shop</a><a href="/installation">Installation</a><a href="/gallery">Gallery</a><a href="/contact">Contact Us</a></nav><a aria-label="Cart" class="cart-link" href="/cart"><i class="fas fa-shopping-cart"></i><span class="badge">0</span></a></div></header>
HTML;
$main = <<<'HTML'
<main><section class="page-hero hero-image-selected" style="--hero-desktop:url('assets/images/hero-selected/privacy-policy-1920.webp');--hero-tablet:url('assets/images/hero-selected/privacy-policy-1440.webp');--hero-mobile:url('assets/images/hero-selected/privacy-policy-960.webp');--hero-position:center center;--hero-position-mobile:58% center;"><span class="eyebrow">Legal</span><h1>Privacy Policy</h1></section><section class="section"><div class="shell content-box"><h2>Information We Collect</h2><p>We collect information you provide when contacting us, requesting a quotation, placing an order, or subscribing to updates. This may include your name, contact details, delivery address, product interest, message, and any attachment you choose to send.</p><h2>How We Use Information</h2><p>We use this information to respond to enquiries, prepare quotations, process orders, arrange delivery or installation, and provide customer support. Attachments supplied with enquiries are stored in a private area and are available only to authorised administrators handling the enquiry.</p><h2>Sharing and Security</h2><p>We do not sell personal information. Information may be shared with trusted service providers only where necessary to fulfil your request or comply with legal obligations. We use access controls, private attachment storage, and other reasonable safeguards to protect the information we hold.</p><h2>Retention and Your Choices</h2><p>We keep information only for as long as reasonably necessary for the purpose for which it was collected, legal obligations, and legitimate business records. You may ask us to access, correct, or delete your personal information, subject to applicable law.</p><h2>Contact</h2><p>For privacy questions, email <a class="gold" href="mailto:info@fireanddine.co.za">info@fireanddine.co.za</a>.</p><p><small>Last updated: 18 August 2026.</small></p></div></section><section class="cta site-final-cta" style="background-image:linear-gradient(rgba(5,6,6,.78),rgba(5,6,6,.92)),url('assets/images/fire-and-dine/cta/cta-05-request-quote.webp');"><div class="shell"><span class="eyebrow">Start your project</span><h2>Bring Your Fire &amp; Dine Space to Life</h2><p>Tell us about your space, preferred product and location, and our team will help you plan the right next step.</p><div class="actions"><a class="btn btn-gold" href="/contact?subject=quote">Request a Quote</a></div></div></section></main>
HTML;
$footer = <<<'HTML'
<footer class="footer"><div class="shell footer-grid"><div class="footer-col footer-brand"><img alt="Fire &amp; Dine — Family Time Since 2013" class="footer-logo" src="assets/images/logo/fire-dine-footer-logo.webp"/></div><div class="footer-col"></div><div class="footer-col footer-contact"><h3>Contact Us</h3><p>Vanderbijlpark, Gauteng</p><a href="tel:+27834381485">083 438 1485</a><a href="mailto:Info@fireanddine.co.za">Info@fireanddine.co.za</a></div><div class="footer-col"><h3>Connect</h3></div><div class="footer-col policy-links"><h3>Policies</h3><a href="/privacy-policy"><i aria-hidden="true" class="fas fa-user-shield gold"></i><span>Privacy Policy</span></a><a href="/terms"><i aria-hidden="true" class="fas fa-file-contract gold"></i><span>Terms of Service</span></a></div></div><div class="copyright"><span class="copyright-sep">|</span><a class="gold" href="/privacy-policy">Privacy Policy</a></div></footer></div>
HTML;
$scripts = <<<'HTML'
<script src="assets/js/fire-dine-premium.js"></script><script src="/assets/js/x3-tracking.js"></script><script src="/assets/js/brochure-widget.js"></script>
HTML;
require dirname(__DIR__) . '/layouts/app.php';
