<?php
declare(strict_types=1);

$bodyAttributes = ' data-landing="residential"';
$head = <<<'HTML'

  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <link href="assets/images/logo/fire-dine-site-icon.webp" rel="icon" type="image/webp"><link href="assets/images/logo/fire-dine-site-icon.webp" rel="apple-touch-icon">
  <title>Residential Pizza Ovens | Fire &amp; Dine</title><meta name="description" content="Explore residential pizza ovens for patios, outdoor kitchens and home entertainment spaces."><link href="https://fireanddine.co.za/residential-pizza-ovens" rel="canonical">
  <link href="assets/fonts/fontawesome/css/all.min.css" rel="stylesheet"><link href="assets/css/fire-dine-premium.css" rel="stylesheet"><link href="/assets/css/design-system.css" rel="stylesheet"/>

HTML;
$header = <<<'HTML'
<div class="page"><header class="header"><div class="shell"><a class="logo" href="/"><img alt="Fire &amp; Dine - Family Time Since 2013" src="assets/images/logo/fire-dine-header-logo.webp"></a><button aria-expanded="false" aria-label="Open navigation" class="menu-btn"><i class="fas fa-bars"></i></button><nav aria-label="Primary navigation" class="nav"><a href="/">Home</a><a href="/about">About Us</a><a href="/shop">Shop</a><a href="/installation">Installation</a><a href="/gallery">Gallery</a><a href="/contact">Contact Us</a></nav><a aria-label="Cart" class="cart-link" href="/cart"><i class="fas fa-shopping-cart"></i><span class="badge">0</span></a></div></header>
HTML;
$main = <<<'HTML'
<main>
    <section class="page-hero hero-image-selected" style="--hero-desktop:url('assets/images/fire-and-dine/range-heroes/residential-pizza-ovens-1916.webp');--hero-tablet:url('assets/images/fire-and-dine/range-heroes/residential-pizza-ovens-1440.webp');--hero-mobile:url('assets/images/fire-and-dine/range-heroes/residential-pizza-ovens-960.webp');--hero-position:center center;--hero-position-mobile:62% center;"><div class="shell"><span class="eyebrow">Home entertaining</span><h1>Residential Pizza Ovens for Memorable Gatherings</h1><p>Compare home pizza ovens around your available space, preferred installation, cooking plans and delivery location.</p><div class="actions"><a class="btn btn-gold" href="/shop#pizza-ovens">View Residential Options</a><a class="btn btn-outline" href="/contact?product=Residential%20Pizza%20Oven">Request a Quote</a></div></div></section>
    <section class="section"><div class="shell"><header class="section-head"><span class="eyebrow">Plan with confidence</span><h2>Start With Your Space and How You Entertain</h2><p>Bring measurements, access details and photographs when requesting product or installation guidance.</p></header><div class="cards"><article class="content-box"><h2>Available Space</h2><p>Confirm footprint, supporting base and access to the planned cooking area.</p></article><article class="content-box"><h2>Cooking Plans</h2><p>Consider typical group size, cooking frequency and the experience you want to create.</p></article><article class="content-box"><h2>Finish and Setting</h2><p>Ask which finish and configuration options apply to your selected product.</p></article></div></div></section>
    <section class="section fd-alt-white" data-kt-integrated="true"><div class="shell"><header class="section-head"><span class="eyebrow">Domestic range</span><h2>DIY and Countertop Options for Home Entertaining</h2><p>For a patio, braai area, boma or outdoor kitchen, start with the available footprint and whether you want a built-in base or finished countertop.</p></header><div class="knowledge-grid"><article class="content-box"><h3>DIY Standard</h3><p>930 mm x 820 mm front to back. Supplied as an assembled dome-and-floor unit.</p></article><article class="content-box"><h3>DIY Grande</h3><p>The middle model in the DIY range. Final dimensions should be confirmed with Fire and Dine before base construction.</p></article><article class="content-box"><h3>DIY Superior</h3><p>1200 mm x 1000 mm. Supplied as an assembled dome-and-floor unit.</p></article><article class="content-box"><h3>Countertop</h3><p>Designed to sit on a finished counter or built-in braai top.</p></article></div><div class="supporting-note"><strong>Included on domestic DIY ovens:</strong> floor insulation, mild-steel door with thermometer, and 430 stainless-steel flue and pipe. Delivery and installation are quoted separately.</div></div></section>
    <section class="section" data-kt-integrated="true"><div class="shell"><header class="section-head"><span class="eyebrow">Base planning</span><h2>Plan the Stand Before Delivery</h2><p>Fire and Dine does not build stands, but can supply diagrams for demonstration and may recommend a builder.</p></header><div class="fact-grid three"><article><strong>Small</strong><span>1.0 m x 1.0 m x 1.1 m high</span></article><article><strong>Medium</strong><span>1.1 m x 1.1 m x 1.1 m high</span></article><article><strong>Large</strong><span>1.2 m x 1.3 m x 1.1 m high</span></article></div><p class="supporting-note"><strong>Coastal projects:</strong> ask about the Coastal Kit with aluminium door, aluminium spigot valve, brushed storm cowl and 304 stainless-steel flue pipe.</p></div></section>
    <section class="cta site-final-cta" style="background-image:linear-gradient(rgba(5,6,6,.78),rgba(5,6,6,.92)),url('assets/images/fire-and-dine/cta/cta-02-shop-pizza-ovens.webp');"><div class="shell"><span class="eyebrow">Your home project</span><h2>Find the Right Oven for Your Space</h2><p>Share measurements, location and intended use for a more relevant conversation.</p><div class="actions"><a class="btn btn-gold" href="/contact?product=Residential%20Pizza%20Oven">Request a Quote</a><a class="btn btn-outline" href="https://wa.me/27834381485">WhatsApp Our Team</a></div></div></section>
  </main>
HTML;
$footer = <<<'HTML'
<footer class="footer"><div class="shell footer-grid"><div class="footer-col footer-brand"><img alt="Fire &amp; Dine - Family Time Since 2013" class="footer-logo" src="assets/images/logo/fire-dine-footer-logo.webp"></div><div class="footer-col policy-links"><h3>Policies</h3><a href="/privacy-policy"><i aria-hidden="true" class="fas fa-user-shield gold"></i><span>Privacy Policy</span></a><a href="/terms"><i aria-hidden="true" class="fas fa-file-contract gold"></i><span>Terms of Service</span></a></div></div><div class="copyright"><span class="copyright-sep">|</span><a class="gold" href="/privacy-policy">Privacy Policy</a></div></footer></div>
HTML;
$scripts = <<<'HTML'
<script src="assets/js/fire-dine-premium.js"></script><script src="/assets/js/x3-tracking.js"></script><script src="/assets/js/brochure-widget.js"></script>

HTML;
require dirname(__DIR__) . '/layouts/app.php';
