<?php
declare(strict_types=1);

$head = <<<'HTML'
<meta charset="utf-8"/><meta content="width=device-width,initial-scale=1" name="viewport"/><title>StoneSkin Decorative Stone Coating | Fire &amp; Dine</title><meta content="Explore StoneSkin decorative stone coating from Fire and Dine for patios, pool surrounds, entertainment areas, braai and boma walls and feature walls." name="description"/><link href="https://fireanddine.co.za/stoneskin" rel="canonical"/><link href="assets/fonts/fontawesome/css/all.min.css" rel="stylesheet"/><link href="assets/css/fire-dine-premium.css" rel="stylesheet"/><link href="/assets/css/design-system.css" rel="stylesheet"/><link href="assets/images/logo/fire-dine-site-icon.webp" rel="icon" type="image/webp"/><link href="assets/images/logo/fire-dine-site-icon.webp" rel="apple-touch-icon"/>
HTML;
$header = <<<'HTML'
<div class="page"><header class="header"><div class="shell"><a class="logo" href="/"><img alt="Fire &amp; Dine — Family Time Since 2013" src="assets/images/logo/fire-dine-header-logo.webp"/></a><button aria-expanded="false" aria-label="Open navigation" class="menu-btn"><i class="fas fa-bars"></i></button><nav aria-label="Primary navigation" class="nav"></nav><a aria-label="Cart" class="cart-link" href="/cart"><i class="fas fa-shopping-cart"></i><span class="badge">0</span></a></div></header>
HTML;
$main = <<<'HTML'
<main><section class="page-hero"><div class="shell"><span class="eyebrow">Durable decorative stone coating</span><h1>StoneSkin</h1><p>A hard-wearing decorative finish used on Fire and Dine ovens and suited to selected outdoor, entertainment and feature surfaces.</p></div></section>
<section class="stoneskin-showcase"><div class="shell"><div class="stoneskin-showcase-grid"><div class="stoneskin-showcase-copy"><span class="eyebrow"><i class="fas fa-fire" aria-hidden="true"></i> StoneSkin <i class="fas fa-fire" aria-hidden="true"></i></span><h2>A Durable Stone Finish for Outdoor Living</h2><span class="stoneskin-rule" aria-hidden="true"></span><p class="stoneskin-lead">StoneSkin is the decorative stone coating used on Fire &amp; Dine ovens and is also suited to pool surrounds, patios, entertainment areas, braai and boma walls, and feature walls.</p><ul class="stoneskin-benefits"><li>Five colours: Quartz, Granite, Midnight Black, New Kalahari and Red Glass</li><li>1.2 mm smooth or 1.6 mm textured aggregate</li><li>Approximately 5 m² coverage per 20 kg bucket</li><li>UV resistant, colourfast and maintenance free</li></ul><a class="btn btn-gold" href="/contact?subject=stoneskin">Explore StoneSkin <span aria-hidden="true">→</span></a></div><div class="stoneskin-panel"><span class="stoneskin-panel-kicker">Fire &amp; Dine Finish</span><span class="stoneskin-panel-rule" aria-hidden="true"></span><h3>Built for Outdoor Spaces.</h3><p>Available as a durable, decorative alternative to paint for suitable prepared surfaces.</p><div class="stoneskin-swatches" aria-label="StoneSkin colour finishes"><div class="stoneskin-swatch stoneskin-swatch--quartz"><div class="stoneskin-swatch-sample" aria-hidden="true"></div><strong>Quartz</strong></div><div class="stoneskin-swatch stoneskin-swatch--granite"><div class="stoneskin-swatch-sample" aria-hidden="true"></div><strong>Granite</strong></div><div class="stoneskin-swatch stoneskin-swatch--midnight"><div class="stoneskin-swatch-sample" aria-hidden="true"></div><strong>Midnight Black</strong></div><div class="stoneskin-swatch stoneskin-swatch--kalahari"><div class="stoneskin-swatch-sample" aria-hidden="true"></div><strong>New Kalahari</strong></div><div class="stoneskin-swatch stoneskin-swatch--red"><div class="stoneskin-swatch-sample" aria-hidden="true"></div><strong>Red Glass</strong></div></div></div></div></div></section>
<section class="section fd-alt-white"><div class="shell"><header class="section-head"><span class="eyebrow">Where it works</span><h2>From the Oven to the Entertainment Area</h2><p>Use StoneSkin to bring a consistent, stone-textured finish into the surfaces around the way you entertain.</p></header><div class="range-cards four"><article><h3>Pool surrounds</h3><p>Decorative finish for suitable prepared surfaces around pool and leisure areas.</p></article><article><h3>Patios</h3><p>A durable coating option for outdoor living and entertainment spaces.</p></article><article><h3>Braai &amp; boma walls</h3><p>Bring the Fire and Dine finish language into braai areas and boma walls.</p></article><article><h3>Feature walls</h3><p>Add a textured stone finish to selected interior or exterior feature surfaces.</p></article></div></div></section><section class="section"><div class="shell"><header class="section-head"><span class="eyebrow">Application support</span><h2>Prepare the Surface Properly</h2><p>Fire and Dine maintains a Surface Prep &amp; Application Guide and Technical Data Sheet TDS-SS-001 Rev 1.1 for StoneSkin. Request the current documents before application.</p></header><div class="warning-box"><strong>Terminology matters.</strong><p>StoneSkin is Fire and Dine's product name and should not be described using competitor coating terminology.</p></div><div class="actions centred-actions"><a class="btn btn-gold" href="/contact?subject=stoneskin">Ask about StoneSkin</a></div></div></section><section class="cta site-final-cta" style="background-image:linear-gradient(rgba(5,6,6,.78),rgba(5,6,6,.92)),url('assets/images/fire-and-dine/cta/cta-05-request-quote.webp');"><div class="shell"><span class="eyebrow">Start your project</span><h2>Bring Your Fire &amp; Dine Space to Life</h2><p>Tell us about your space, preferred product and location, and our team will help you plan the right next step.</p><div class="actions"><a class="btn btn-gold" href="/contact?subject=quote">Request a Quote</a></div></div></section></main>
HTML;
$footer = <<<'HTML'
<footer class="footer"><div class="shell footer-grid"><div class="footer-col footer-brand"><img alt="Fire &amp; Dine — Family Time Since 2013" class="footer-logo" src="assets/images/logo/fire-dine-footer-logo.webp"/></div><div class="footer-col"><h3>Quick Links</h3><a href="/pizza-ovens">Pizza Ovens</a><a href="/fireplaces">Fireplaces</a><a href="/stoneskin">StoneSkin</a><a href="/installation">Installation</a></div><div class="footer-col footer-contact"><h3>Contact Us</h3><p>Vanderbijlpark, Gauteng</p><a href="tel:+27834381485">083 438 1485</a><a href="mailto:Info@fireanddine.co.za">Info@fireanddine.co.za</a></div><div class="footer-col policy-links"><h3>Policies</h3><a href="/privacy-policy">Privacy Policy</a><a href="/terms">Terms of Service</a></div></div><div class="copyright">© <span data-year=""></span> Fire &amp; Dine (Pty) Ltd · Family Time Since 2013</div></footer></div>
HTML;
$scripts = <<<'HTML'
<script src="assets/js/fire-dine-premium.js"></script><script src="/assets/js/x3-tracking.js"></script><script src="/assets/js/brochure-widget.js"></script><script src="/assets/js/stoneskin-brand-cleanup.js"></script>
HTML;
require dirname(__DIR__) . '/layouts/app.php';
