<?php
declare(strict_types=1);

$head = <<<'HTML'
<meta charset="utf-8"/><meta content="width=device-width,initial-scale=1" name="viewport"/><link href="assets/images/logo/fire-dine-site-icon.webp" rel="icon" type="image/webp"/><link href="assets/images/logo/fire-dine-site-icon.webp" rel="apple-touch-icon"/><title>Terms &amp; Conditions | Fire &amp; Dine</title><meta content="Premium wood-fired ovens, fireplaces and installations in South Africa." name="description"/><link href="assets/fonts/fontawesome/css/all.min.css" rel="stylesheet"/><link href="assets/css/fire-dine-premium.css" rel="stylesheet"/><link href="/assets/css/design-system.css" rel="stylesheet"/>
HTML;
$header = <<<'HTML'
<div class="page"><header class="header"><div class="shell"><a class="logo" href="/"><img alt="Fire &amp; Dine — Family Time Since 2013" src="assets/images/logo/fire-dine-header-logo.webp"/></a><button aria-expanded="false" aria-label="Open navigation" class="menu-btn"><i class="fas fa-bars"></i></button><nav aria-label="Primary navigation" class="nav"><a href="/">Home</a><a href="/about">About Us</a><a href="/shop">Shop</a><a href="/installation">Installation</a><a href="/gallery">Gallery</a><a href="/contact">Contact Us</a></nav><a aria-label="Cart" class="cart-link" href="/cart"><i class="fas fa-shopping-cart"></i><span class="badge">0</span></a></div></header>
HTML;
$main = <<<'HTML'
<main><section class="page-hero hero-image-selected" style="--hero-desktop:url('assets/images/hero-selected/terms-of-service-1920.webp');--hero-tablet:url('assets/images/hero-selected/terms-of-service-1440.webp');--hero-mobile:url('assets/images/hero-selected/terms-of-service-960.webp');--hero-position:center center;--hero-position-mobile:50% center;"><h1>Terms &amp; Conditions</h1></section><section class="section"><div class="shell content-box" style="max-width:1000px"><h2>1. General</h2><p>These terms govern use of the Fire &amp; Dine website and the purchase of products and services. Product availability, specifications and pricing may change without notice.</p><h2>2. Quotations and Orders</h2><p>Quotations and Orders are confirmed in writing. Deposit requirements, payment terms and lead times are project-specific and must be confirmed in the applicable quotation or order documentation.</p><h2>3. Delivery and Installation</h2><p>Delivery and installation are excluded from listed oven prices and are quoted separately per job. The final scope depends on destination, access, site readiness and the selected product.</p><h2>4. Returns and Warranties</h2><p>Warranty, guarantee and return terms are not stated as universal terms in the current website source material. Confirm the terms that apply to your product in the written quotation, invoice or product documentation before purchase.</p><h2>5. Safety and Maintenance</h2><p>Products must be operated according to supplied instructions and maintained at appropriate intervals.</p><h2>6. Contact</h2><p>Questions may be sent to info@fireanddine.co.za.</p></div></section><section class="cta site-final-cta" style="background-image:linear-gradient(rgba(5,6,6,.78),rgba(5,6,6,.92)),url('assets/images/fire-and-dine/cta/cta-05-request-quote.webp');"><div class="shell"><span class="eyebrow">Start your project</span><h2>Bring Your Fire &amp; Dine Space to Life</h2><p>Tell us about your space, preferred product and location, and our team will help you plan the right next step.</p><div class="actions"><a class="btn btn-gold" href="/contact?subject=quote">Request a Quote</a></div></div></section></main>
HTML;
$footer = <<<'HTML'
<footer class="footer"><div class="shell footer-grid"><div class="footer-col footer-brand"><img alt="Fire &amp; Dine — Family Time Since 2013" class="footer-logo" src="assets/images/logo/fire-dine-footer-logo.webp"/></div><div class="footer-col"><h3>Quick Links</h3><a href="/installation#maintenance"><i aria-hidden="true" class="fas fa-wrench gold"></i><span>Maintenance</span></a><a href="/contact"><i aria-hidden="true" class="fas fa-phone gold"></i><span>Contact Us</span></a><a href="/"><i aria-hidden="true" class="fas fa-home gold"></i><span>Home</span></a><a href="/shop"><i aria-hidden="true" class="fas fa-shopping-bag gold"></i><span>Shop</span></a><a href="/stoneskin">StoneSkin</a></div><div class="footer-col footer-contact"><h3>Contact Us</h3><p><i aria-hidden="true" class="fas fa-map-marker-alt gold"></i><span>Vanderbijlpark, Gauteng</span></p><a href="tel:+27834381485"><i aria-hidden="true" class="fas fa-phone gold"></i><span>083 438 1485</span></a><a href="mailto:Info@fireanddine.co.za"><i aria-hidden="true" class="fas fa-envelope gold"></i><span>Info@fireanddine.co.za</span></a></div><div class="footer-col"><h3>Connect</h3><div class="socials"><a aria-label="Contact Fire &amp; Dine" href="/contact"><i class="fab fa-facebook-f"></i></a><a aria-label="Contact Fire &amp; Dine" href="/contact"><i class="fab fa-instagram"></i></a><a aria-label="Contact Fire &amp; Dine" href="/contact"><i class="fab fa-youtube"></i></a></div></div><div class="footer-col policy-links"><h3>Policies</h3><a href="/privacy-policy"><i aria-hidden="true" class="fas fa-user-shield gold"></i><span>Privacy Policy</span></a><a href="/terms"><i aria-hidden="true" class="fas fa-file-contract gold"></i><span>Terms of Service</span></a></div></div><div class="copyright"><span>© South Africa <span data-year=""></span></span><span class="copyright-sep">|</span><span>All Rights Reserved</span><span></span><span class="copyright-sep">|</span><a class="gold" href="/terms">Terms &amp; Conditions</a><span class="copyright-sep">|</span><a class="gold" href="/privacy-policy">Privacy Policy</a></div></footer></div>
HTML;
$scripts = <<<'HTML'
<script src="assets/js/fire-dine-premium.js"></script><script src="/assets/js/x3-tracking.js"></script><script src="/assets/js/brochure-widget.js"></script>
HTML;
require dirname(__DIR__) . '/layouts/app.php';
